import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import configureStore from '../components/store.ts'
import { ITaskState, STATUS_TYPES } from '../components/types.ts'
import { Provider } from 'react-redux'
import { Normalize } from 'styled-normalize'
import Header from '../components/Header'
import Main from '../components/Main'
import StatusBoard from '../components/StatusBoard.tsx'

export default function Home() {
	const store = configureStore()

  return (
    <div className={styles.container}>
	    <Head>
        <title>Keza Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
		    <Provider store={store}>
	  	  	<Header />
			    <StatusBoard />
		    </Provider>
      </main>
    </div>
  )
}
